# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- release

pool:
  vmImage: 'macos-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $content = 'API_KEY_ALPHAVANTAGE=$env:API_KEY_ALPHAVANTAGE' + "`n" +
                 'API_KEY_NEWS=$env:API_KEY_NEWS' + "`n" +
                 'API_KEY_RECIPE=$env:API_KEY_RECIPE' + "`n"

      Set-Content -Path "$(System.DefaultWorkingDirectory)/local.properties" -Value $content

- task: Gradle@2
  inputs:
    workingDirectory: '$(system.defaultWorkingDirectory)/app'
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
- task: PublishBuildArtifacts@1